# Generated by Django 4.0 on 2022-01-06 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, null='False', unique=True)),
                ('year', models.IntegerField(default=2022)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null='False')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null='False')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null='False')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('clusterlevel', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.clusterlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15)),
                ('total_days', models.IntegerField(null='False')),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('year', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='terms_of_year', to='pay.year')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='New Profile', max_length=25, null='False')),
                ('last_name', models.CharField(max_length=15, null='False')),
                ('address', models.CharField(blank=True, max_length=50, null='True')),
                ('age', models.IntegerField(null='False')),
                ('tell', models.IntegerField(blank=True, default=None, null='True')),
                ('cell', models.IntegerField(blank=True, default=None, null='True')),
                ('is_preschool', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='profiles_of_classroom', to='pay.classroom')),
                ('gender', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.gender')),
                ('level', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('Swipe', 'RTGS Swipe'), ('USD', 'USD'), ('Rand', 'Rand')], max_length=10)),
                ('particular', models.CharField(choices=[('Tuition', 'Tuition'), ('Groceries', 'Groceries'), ('Development', 'Development'), ('Online Learning', 'Online Learning'), ('Bus Levy', 'Bus Levy')], max_length=100)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('Novemver', 'Novemver'), ('December', 'December')], max_length=100, null='True')),
                ('client_name', models.CharField(max_length=30, null='False')),
                ('address', models.CharField(blank=True, default='', max_length=50, null='True')),
                ('phone_number', models.IntegerField(blank=True, null='True')),
                ('amount_paid', models.IntegerField(null='False')),
                ('actual_amount_paid', models.IntegerField(blank=True, null='True')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('cashier', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='profile_cashier', to='pay.profile')),
                ('profile', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.profile')),
                ('term', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='payments_of_terms', to='pay.term')),
            ],
        ),
        migrations.CreateModel(
            name='GroceriesForTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null='True')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('clusterlevel', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.clusterlevel')),
                ('term', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='pay.term')),
            ],
        ),
        migrations.CreateModel(
            name='FeesForTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null='True')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('clusterlevel', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.clusterlevel')),
                ('term', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.term')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.profile')),
                ('term', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pay.term')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pay.level'),
        ),
    ]
