# Generated by Django 4.0 on 2022-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin_pay',
            field=models.BooleanField(default=False),
        ),
    ]
