# Generated by Django 4.0 on 2022-01-06 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('Rand', 'Rand'), ('USD', 'USD'), ('RTGS', 'RTGS')], default='USD', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(default='', max_length=120, verbose_name='Customer Name')),
                ('line_one', models.CharField(choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, verbose_name='Line 1')),
                ('line_one_quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('line_one_unit_price', models.IntegerField(default=0, verbose_name='Unit Price')),
                ('line_one_total_price', models.IntegerField(default=0, verbose_name='Line Total')),
                ('line_two', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 2')),
                ('line_two_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_two_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_two_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_three', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 3')),
                ('line_three_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_three_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_three_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_four', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 4')),
                ('line_four_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_four_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_four_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_five', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 5')),
                ('line_five_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_five_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_five_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_six', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 6')),
                ('line_six_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_six_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_six_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_seven', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 7')),
                ('line_seven_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_seven_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_seven_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_eight', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 8')),
                ('line_eight_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_eight_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_eight_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_nine', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 9')),
                ('line_nine_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_nine_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_nine_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('line_ten', models.CharField(blank=True, choices=[('Satchel ECD', 'Satchel ECD'), ('Satchel Primary', 'Satchel Primary'), ('Jersey', 'Jersey'), ('Sunhat', 'Sunhat'), ('Sports Wear', 'Sports Wear'), ('Anorak', 'Anorak'), ('Masks', 'Masks'), ('Shield', 'Shield'), ('Tie', 'Tie'), ('Blazer', 'Blazer'), ('Summer Uniform ECD', 'Summer Uniform ECD'), ('Winter Uniform ECD', 'Winter Uniform ECD'), ('Summer Dress Primary', 'Summer Dress Primary'), ('Summer Shirts Primary', 'Summer Shirts Primary'), ('Winter Shirts Primary', 'Winter Shirts Primary'), ('TrackSuit', 'TrackSuit')], default='', max_length=120, null=True, verbose_name='Line 10')),
                ('line_ten_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_ten_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_ten_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total')),
                ('phone_number', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('total', models.IntegerField(blank=True, default='0', null=True)),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice'), ('Invoice', 'Invoice')], default='Receipt', max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
